### ISSUE TITLE
problems with socket.io 1.4.x

### ISSUE THREAD

**Issue by shackbarth** [balderdashy/sails-hook-sockets#18]
Websockets suddenly stopped working with my latest production deploy. It's possibly the same problem as reported here: https://github.com/socketio/socket.io/issues/2378 although it's tough to say, because, as with that thread, there's no error message.

When I monkeyed my node_modules back to socketio 1.3.x everything started working again.

I'm pegged on sails version 0.11.2 (so: sails-hook-sockets 0.11.28). It looks like sails 0.11.4 has some updates in this area, so I'll upgrade on my next release and hopefully the problem will go away. 

But if it's not just me, if other people have this problem, then unless you release a 0.11.29 with tighter socket-io pegging then sails 0.11.2 is going to be broken for all time, websocketwise. And if that's the case I would say please please stop using carats -- and maybe even tildes -- on your socketio dependency.

**Comment by sgress454** [comment]
> please please stop using carats -- and maybe even tildes -- on your socketio dependency.

Lesson learned, believe me.  Recently [some vulnerabilities were pointed out](https://github.com/balderdashy/sails/issues/3464) in some dependencies (and sub-dependencies) of Sails, including socket.io.  In response, socket.io put out a patch (quickly, thanks to @rauchg) as v1.4.0, and we followed suit with 11.4.  Unfortunately, socket.io v1.4 had some breaking changes for us, sails-hook-sockets had already been bumped to v0.12.0, and because of the way semver carats work on 0.x releases, Sails < 11.4 gets shafted.

Thanks for pointing this out.  For your part, I think you can safely upgrade to 11.4--the only changes are the [aforementioned security patches](https://github.com/balderdashy/sails/issues/3464) and the ability to install/run Sails in NPM 3+ environments.  But for folks who are in the dark about all this, I'll attempt to publish a sails-hook-sockets v0.11.29 that will peg the socket.io dependency to 1.3.7 so that installs don't break.

**Comment by sgress454** [comment]
Ok--published v0.11.29 which just locks socket.io and socket.io-client to 1.3.7, so future deployments of Sails < 0.11.4 should work.  But it's still recommended that you upgrade!

**Comment by sgress454** [comment]
@shackbarth  Also forgot to mention: because `sails-hook-sockets` is a separate module from Sails, you can always override the default version by installing it directly into your project.  That is, even with a 0.11.3 Sails install, you can `npm i sails-hook-sockets 0.12.3` directly into your project and it will work (and solve this issue).

**Comment by luislobo** [comment]
hey @sgress454 I don't see v0.11.29 tagged, is it?

**Comment by luislobo** [comment]
Also, what about updating https://github.com/balderdashy/sails.io.js?

**Comment by sgress454** [comment]
@luislobo thanks for the heads-up, just tagged.  I don't think we need to do anything with sails.io.js; the breaking changes in socket.io only affected the server-side `sails.sockets.*` methods as far as I can tell.   Some of those are apparently using undocumented socket.io features.  We'll be deprecating those methods to ensure that this doesn't happen again!
