### ISSUE TITLE
Error when session hook is disabled

### ISSUE THREAD

**Issue by TomKaltz** [balderdashy/sails-hook-sockets#3]
https://github.com/balderdashy/sails-hook-sockets/blob/master/lib/load-session-from-socket.js#L43

I'm using my own JWT-based "session" middleware and have disabled the sails session hook.  I'm wondering if this hook should check to see if the session hook exists before throwing these errors.

**Comment by mikermcneil** [comment]
Hey @TomKaltz, that code should never run because of an [early `return` higher up in the `loadSessionFromSocket` function](https://github.com/balderdashy/sails-hook-sockets/blob/master/lib/load-session-from-socket.js#L16)

I haven't been able to replicate an issue-- [here is the test](https://github.com/balderdashy/sails-hook-sockets/blob/master/test/without-session.test.js#L42) we're currently using to verify that sockets work w/o needing a session.  Would you mind taking a pass at replicating the error you're seeing there?

Thanks!

**Comment by mikermcneil** [comment]
@TomKaltz heads up- after you clone this repo, cd into it, and `npm install`, to run _all_ the tests, you'll want to first start a local redis server on port 6380 (`redis-server --port 6380`).  And then run `npm test`.

Alternatively, if you don't have redis installed locally, you can run that particular test with `node ./node_modules/mocha/bin/mocha -g 'without session'` and skip the redis step.

**Comment by mikermcneil** [comment]
@TomKaltz you should see:


```
sails-hook-sockets: ∑ node ./node_modules/mocha/bin/mocha -g 'without session'


  without session
    when a new socket is connected
      ✓ should not crash 
warn: `sails.config.sockets.onConnect` has been deprecated, and support will be removed in an upcoming release. See the v0.11 migration guide for more information.
warn: (running it for you this time)
      ✓ should trigger onConnect lifecycle event 
      ✓ should stub out an empty object for the session argument 
      ✓ should provide access to socket 
      ✓ should not crash after flinging a bunch of requests at it 
      ✓ should respond to requests as expected (138ms)
    when a socket is disconnected
      ✓ should trigger onDisconnect lifecycle event (1003ms)
      ✓ should stub out an empty object for the session argument 
      ✓ should provide access to socket 


  9 passing (2s)


```
